// Generated from the school system's API description. Field kinds drive the admin forms.
part of 'admin_manage_pages.dart';

const fieldLabelsAr = <String, String>{
  'access': 'الصلاحية',
  'action': 'الإجراء',
  'actionRequired': 'إجراء مطلوب',
  'active': 'نشط',
  'activeApplicationForm': 'نشط في نموذج التقديم',
  'activeDataUpdater': 'نشط في تحديث البيانات',
  'activePersonOther': 'نشط لغيرهم',
  'activePersonParent': 'نشط لولي الأمر',
  'activePersonStaff': 'نشط للموظفين',
  'activePersonStudent': 'نشط للطلاب',
  'address1': 'العنوان',
  'address1Country': 'الدولة',
  'address1District': 'المنطقة',
  'allowFileUpload': 'السماح برفع ملف',
  'amount': 'المبلغ',
  'attachment': 'مرفق',
  'attainment': 'التحصيل',
  'attainmentConcern': 'مخاوف التحصيل',
  'attainmentDescriptor': 'وصف التحصيل',
  'attainmentValue': 'درجة التحصيل',
  'attainmentValueRaw': 'الدرجة الخام',
  'attendance': 'الحضور',
  'body': 'النص',
  'canLogin': 'يمكنه الدخول',
  'category': 'الفئة',
  'childDataAccess': 'الوصول لبيانات الأبناء',
  'comment': 'تعليق',
  'companyAddress': 'عنوان الشركة',
  'companyAll': 'كل الرسوم على الشركة',
  'companyCCFamily': 'نسخة للأسرة',
  'companyContact': 'مسؤول الشركة',
  'companyEmail': 'بريد الشركة',
  'companyName': 'اسم الشركة',
  'companyPhone': 'هاتف الشركة',
  'complete': 'مكتمل',
  'completeDate': 'تاريخ الاكتمال',
  'confidential': 'سري',
  'contactCall': 'تواصل بالاتصال',
  'contactEmail': 'تواصل بالبريد',
  'contactMail': 'تواصل بالمراسلة',
  'contactPriority': 'أولوية التواصل',
  'contactSMS': 'تواصل بالرسائل',
  'context': 'السياق',
  'countryOfBirth': 'بلد الميلاد',
  'date': 'التاريخ',
  'dateEnd': 'تاريخ الانتهاء',
  'dateEnrolled': 'تاريخ التسجيل',
  'dateStart': 'تاريخ البدء',
  'dateUnenrolled': 'تاريخ الانسحاب',
  'description': 'الوصف',
  'descriptor': 'الوصف',
  'direction': 'الاتجاه',
  'dob': 'تاريخ الميلاد',
  'document': 'الوثيقة',
  'effort': 'الجهد',
  'effortConcern': 'مخاوف الجهد',
  'effortDescriptor': 'وصف الجهد',
  'effortValue': 'درجة الجهد',
  'email': 'البريد الإلكتروني',
  'emailAlternate': 'بريد بديل',
  'enrolmentMax': 'الحد الأقصى للتسجيل',
  'enrolmentMin': 'الحد الأدنى للتسجيل',
  'fields': 'الحقول',
  'firstName': 'الاسم الأول',
  'followup': 'المتابعة',
  'format': 'الصيغة',
  'gender': 'الجنس',
  'tawasulAttendanceCodeID': 'رمز الحضور',
  'tawasulCourseClassID': 'الفصل',
  'tawasulCourseID': 'المقرر',
  'tawasulDepartmentID': 'القسم',
  'tawasulExternalAssessmentFieldID': 'حقل الاختبار',
  'tawasulExternalAssessmentID': 'الاختبار',
  'tawasulExternalAssessmentStudentID': 'اختبار الطالب',
  'tawasulFamilyID': 'الأسرة',
  'tawasulFinanceBudgetCycleID': 'دورة الميزانية',
  'tawasulFinanceBudgetID': 'الميزانية',
  'tawasulFinanceExpenseID': 'النفقة',
  'tawasulFinanceFeeCategoryIDList': 'فئات الرسوم',
  'tawasulFormGroupID': 'الشعبة',
  'tawasulHouseID': 'البيت',
  'tawasulInternalAssessmentColumnID': 'التقييم الداخلي',
  'tawasulMarkbookColumnID': 'عمود الدرجات',
  'tawasulPersonID': 'الشخص',
  'tawasulPersonID1': 'الشخص الأول',
  'tawasulPersonID2': 'الشخص الثاني',
  'tawasulPersonIDCreated': 'أنشأه',
  'tawasulPersonIDCreator': 'المنشئ',
  'tawasulPersonIDLastEdit': 'آخر من عدّل',
  'tawasulPersonIDModified': 'عدّله',
  'tawasulPersonIDOperator': 'المنفّذ',
  'tawasulPersonIDStatus': 'غيّر الحالة',
  'tawasulPersonIDStudent': 'الطالب',
  'tawasulPersonIDTaker': 'مسجل الحضور',
  'tawasulPersonIDUpdate': 'حدّثه',
  'tawasulPlannerEntryID': 'الدرس',
  'tawasulRoleIDAll': 'كل الأدوار',
  'tawasulRoleIDList': 'الأدوار',
  'tawasulRoleIDPrimary': 'الدور الأساسي',
  'tawasulScaleGradeID': 'درجة المقياس',
  'tawasulScaleID': 'المقياس',
  'tawasulScaleIDAttainment': 'مقياس التحصيل',
  'tawasulScaleIDEffort': 'مقياس الجهد',
  'tawasulScaleIDTarget': 'مقياس الهدف',
  'tawasulSchoolYearID': 'السنة الدراسية',
  'tawasulTTDayRowClassID': 'حصة الجدول',
  'tawasulUnitID': 'الوحدة',
  'tawasulYearGroupIDList': 'الصفوف الدراسية',
  'groupingID': 'رقم المجموعة',
  'homeAddress': 'عنوان المنزل',
  'homeAddressCountry': 'دولة المنزل',
  'homeAddressDistrict': 'منطقة المنزل',
  'homework': 'واجب',
  'homeworkDetails': 'تفاصيل الواجب',
  'homeworkDueDateTime': 'موعد تسليم الواجب',
  'invoiceDueDate': 'تاريخ الاستحقاق',
  'invoiceIssueDate': 'تاريخ الإصدار',
  'invoiceTo': 'الفاتورة إلى',
  'isDefault': 'افتراضي',
  'isNumeric': 'رقمي',
  'key': 'المفتاح',
  'languageFirst': 'اللغة الأولى',
  'languageHomePrimary': 'لغة المنزل الأساسية',
  'languageHomeSecondary': 'لغة المنزل الثانوية',
  'level': 'المستوى',
  'lockerNumber': 'رقم الخزانة',
  'map': 'الخريطة',
  'messageWall': 'لوحة الرسائل',
  'messageWall_dateEnd': 'نهاية العرض',
  'messageWall_dateStart': 'بداية العرض',
  'modifiedAssessment': 'تقييم معدّل',
  'name': 'الاسم',
  'nameAddress': 'اسم المراسلة',
  'nameShort': 'الاسم المختصر',
  'notes': 'ملاحظات',
  'numericIncrement': 'الزيادة الرقمية',
  'numericSize': 'عدد الخانات',
  'numericValue': 'القيمة الرقمية',
  'officialName': 'الاسم الرسمي',
  'order': 'الترتيب',
  'orderBy': 'ترتيب حسب',
  'phone1': 'الهاتف',
  'phone1Type': 'نوع الهاتف',
  'phone2': 'هاتف آخر',
  'preferredName': 'الاسم المفضل',
  'reason': 'السبب',
  'relationship': 'صلة القرابة',
  'reportable': 'قابل للتقرير',
  'required': 'مطلوب',
  'response': 'الرد',
  'role': 'الدور',
  'sequenceNumber': 'التسلسل',
  'sms': 'رسالة نصية',
  'status': 'الحالة',
  'statusNew': 'الحالة الجديدة',
  'statusOld': 'الحالة السابقة',
  'studentID': 'رقم الطالب',
  'subject': 'الموضوع',
  'summary': 'الملخص',
  'surname': 'اسم العائلة',
  'tables': 'الجداول',
  'teachersNotes': 'ملاحظات المعلم',
  'timeEnd': 'وقت الانتهاء',
  'timeStart': 'وقت البدء',
  'timestamp': 'الوقت',
  'timestampCreated': 'وقت الإنشاء',
  'timestampCreator': 'وقت الإنشاء',
  'timestampStatus': 'وقت تغيير الحالة',
  'timestampUpdate': 'وقت التحديث',
  'title': 'اللقب',
  'transport': 'النقل',
  'transportNotes': 'ملاحظات النقل',
  'type': 'النوع',
  'uploadedResponse': 'رد مرفوع',
  'username': 'اسم المستخدم',
  'value': 'القيمة',
  'viewableParents': 'يراه أولياء الأمور',
  'viewableStudents': 'يراه الطلاب',
  'website': 'الموقع',
};

const resourceFields = <String, List<FieldSpec>>{
  '/attendance': [
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulAttendanceCodeID', 'ref:/attendance-codes', required: false, options: [], maxLength: 0),
    FieldSpec('date', 'date', required: true, options: [], maxLength: 0),
    FieldSpec('direction', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('type', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('reason', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('context', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('comment', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDTaker', 'ref:/users', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulFormGroupID', 'ref:/form-groups', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulCourseClassID', 'ref:/classes', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulTTDayRowClassID', 'text', required: false, options: [], maxLength: 0),
  ],
  '/behaviour': [
    FieldSpec('tawasulSchoolYearID', 'ref:/school-years', required: true, options: [], maxLength: 0),
    FieldSpec('date', 'date', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('type', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('descriptor', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('level', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('comment', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('followup', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPlannerEntryID', 'ref:/lessons', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDCreator', 'ref:/users', required: false, options: [], maxLength: 0),
  ],
  '/budgets': [
  ],
  '/class-enrolments': [
    FieldSpec('tawasulCourseClassID', 'ref:/classes', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('role', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('dateEnrolled', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('dateUnenrolled', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('reportable', 'text', required: false, options: [], maxLength: 0),
  ],
  '/classes': [
    FieldSpec('tawasulCourseID', 'ref:/courses', required: true, options: [], maxLength: 0),
    FieldSpec('name', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('nameShort', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('reportable', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('attendance', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('enrolmentMin', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('enrolmentMax', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulScaleIDTarget', 'ref:/scales', required: false, options: [], maxLength: 0),
  ],
  '/courses': [
    FieldSpec('tawasulSchoolYearID', 'ref:/school-years', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulDepartmentID', 'ref:/departments', required: false, options: [], maxLength: 0),
    FieldSpec('name', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('nameShort', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('description', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('map', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulYearGroupIDList', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('orderBy', 'text', required: false, options: [], maxLength: 0),
  ],
  '/data-retentions': [
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('tables', 'long', required: true, options: [], maxLength: 0),
    FieldSpec('status', 'choice', required: false, options: ['Success', 'Partial Failure'], maxLength: 0),
    FieldSpec('timestamp', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDOperator', 'ref:/users', required: true, options: [], maxLength: 0),
  ],
  '/districts': [
    FieldSpec('name', 'text', required: true, options: [], maxLength: 30),
  ],
  '/expenses': [
  ],
  '/external-assessment-fields': [
    FieldSpec('tawasulExternalAssessmentID', 'ref:/external-assessments', required: true, options: [], maxLength: 0),
    FieldSpec('name', 'text', required: true, options: [], maxLength: 50),
    FieldSpec('category', 'text', required: true, options: [], maxLength: 50),
    FieldSpec('order', 'number', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulScaleID', 'ref:/scales', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulYearGroupIDList', 'text', required: false, options: [], maxLength: 255),
  ],
  '/external-assessment-student-entries': [
    FieldSpec('tawasulExternalAssessmentStudentID', 'ref:/external-assessment-students', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulExternalAssessmentFieldID', 'ref:/external-assessment-fields', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulScaleGradeID', 'number', required: false, options: [], maxLength: 0),
  ],
  '/external-assessment-students': [
    FieldSpec('tawasulExternalAssessmentID', 'ref:/external-assessments', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('date', 'date', required: true, options: [], maxLength: 0),
    FieldSpec('attachment', 'text', required: true, options: [], maxLength: 255),
  ],
  '/external-assessments': [
    FieldSpec('name', 'text', required: true, options: [], maxLength: 50),
    FieldSpec('nameShort', 'text', required: true, options: [], maxLength: 10),
    FieldSpec('description', 'long', required: true, options: [], maxLength: 255),
    FieldSpec('website', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('active', 'yn', required: true, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('allowFileUpload', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
  ],
  '/families': [
    FieldSpec('name', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('nameAddress', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('homeAddress', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('homeAddressDistrict', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('homeAddressCountry', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('status', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('languageHomePrimary', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('languageHomeSecondary', 'text', required: false, options: [], maxLength: 0),
  ],
  '/family-adults': [
    FieldSpec('tawasulFamilyID', 'ref:/families', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('comment', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('childDataAccess', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('contactPriority', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('contactCall', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('contactSMS', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('contactEmail', 'email', required: false, options: [], maxLength: 0),
    FieldSpec('contactMail', 'text', required: false, options: [], maxLength: 0),
  ],
  '/family-children': [
    FieldSpec('tawasulFamilyID', 'ref:/families', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('comment', 'long', required: false, options: [], maxLength: 0),
  ],
  '/family-relationships': [
    FieldSpec('tawasulFamilyID', 'ref:/families', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID1', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID2', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('relationship', 'text', required: true, options: [], maxLength: 50),
  ],
  '/fees': [
  ],
  '/finance-billing-schedules': [
    FieldSpec('tawasulSchoolYearID', 'ref:/school-years', required: true, options: [], maxLength: 0),
    FieldSpec('name', 'text', required: true, options: [], maxLength: 100),
    FieldSpec('description', 'long', required: true, options: [], maxLength: 0),
    FieldSpec('active', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('invoiceIssueDate', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('invoiceDueDate', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDCreator', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('timestampCreator', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDUpdate', 'ref:/users', required: false, options: [], maxLength: 0),
    FieldSpec('timestampUpdate', 'datetime', required: false, options: [], maxLength: 0),
  ],
  '/finance-budget-cycle-allocations': [
    FieldSpec('tawasulFinanceBudgetID', 'ref:/budgets', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulFinanceBudgetCycleID', 'ref:/finance-budget-cycles', required: true, options: [], maxLength: 0),
    FieldSpec('value', 'number', required: false, options: [], maxLength: 0),
  ],
  '/finance-budget-cycles': [
    FieldSpec('name', 'text', required: true, options: [], maxLength: 7),
    FieldSpec('status', 'choice', required: false, options: ['Past', 'Current', 'Upcoming'], maxLength: 0),
    FieldSpec('dateStart', 'date', required: true, options: [], maxLength: 0),
    FieldSpec('dateEnd', 'date', required: true, options: [], maxLength: 0),
    FieldSpec('sequenceNumber', 'number', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDCreator', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('timestampCreator', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDUpdate', 'ref:/users', required: false, options: [], maxLength: 0),
    FieldSpec('timestampUpdate', 'datetime', required: false, options: [], maxLength: 0),
  ],
  '/finance-budget-persons': [
    FieldSpec('tawasulFinanceBudgetID', 'ref:/budgets', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('access', 'choice', required: true, options: ['Full', 'Write', 'Read'], maxLength: 0),
  ],
  '/finance-expense-approvers': [
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('sequenceNumber', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDCreator', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('timestampCreator', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDUpdate', 'ref:/users', required: false, options: [], maxLength: 0),
    FieldSpec('timestampUpdate', 'datetime', required: false, options: [], maxLength: 0),
  ],
  '/finance-expense-logs': [
    FieldSpec('tawasulFinanceExpenseID', 'ref:/expenses', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('timestamp', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('action', 'choice', required: true, options: ['Request', 'Approval - Partial - Budget', 'Approval - Partial - School', 'Approval - Final', 'Approval - Exempt', 'Rejection', 'Cancellation', 'Order', 'Payment', 'Reimbursement Request', 'Reimbursement Completion', 'Comment'], maxLength: 0),
    FieldSpec('comment', 'long', required: true, options: [], maxLength: 0),
  ],
  '/finance-fee-categories': [
    FieldSpec('name', 'text', required: true, options: [], maxLength: 100),
    FieldSpec('nameShort', 'text', required: true, options: [], maxLength: 6),
    FieldSpec('description', 'long', required: true, options: [], maxLength: 0),
    FieldSpec('active', 'yn', required: true, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('tawasulPersonIDCreator', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('timestampCreator', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDUpdate', 'ref:/users', required: false, options: [], maxLength: 0),
    FieldSpec('timestampUpdate', 'datetime', required: false, options: [], maxLength: 0),
  ],
  '/finance-invoicees': [
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('invoiceTo', 'choice', required: true, options: ['Family', 'Company'], maxLength: 0),
    FieldSpec('companyName', 'text', required: false, options: [], maxLength: 100),
    FieldSpec('companyContact', 'text', required: false, options: [], maxLength: 100),
    FieldSpec('companyAddress', 'long', required: false, options: [], maxLength: 255),
    FieldSpec('companyEmail', 'email', required: false, options: [], maxLength: 0),
    FieldSpec('companyCCFamily', 'yn', required: false, options: ['N', 'Y'], maxLength: 0),
    FieldSpec('companyPhone', 'text', required: false, options: [], maxLength: 20),
    FieldSpec('companyAll', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('tawasulFinanceFeeCategoryIDList', 'text', required: false, options: [], maxLength: 0),
  ],
  '/finance-petty-cashes': [
    FieldSpec('tawasulSchoolYearID', 'ref:/school-years', required: true, options: [], maxLength: 3),
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('amount', 'number', required: true, options: [], maxLength: 0),
    FieldSpec('reason', 'long', required: false, options: [], maxLength: 90),
    FieldSpec('notes', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDCreated', 'ref:/users', required: false, options: [], maxLength: 0),
    FieldSpec('timestampCreated', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('actionRequired', 'text', required: false, options: [], maxLength: 60),
    FieldSpec('tawasulPersonIDStatus', 'ref:/users', required: false, options: [], maxLength: 0),
    FieldSpec('timestampStatus', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('status', 'text', required: true, options: [], maxLength: 60),
  ],
  '/internal-assessment-columns': [
    FieldSpec('tawasulCourseClassID', 'ref:/classes', required: true, options: [], maxLength: 0),
    FieldSpec('groupingID', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('name', 'text', required: true, options: [], maxLength: 30),
    FieldSpec('description', 'long', required: true, options: [], maxLength: 0),
    FieldSpec('type', 'text', required: true, options: [], maxLength: 50),
    FieldSpec('attachment', 'text', required: true, options: [], maxLength: 255),
    FieldSpec('attainment', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('tawasulScaleIDAttainment', 'ref:/scales', required: false, options: [], maxLength: 0),
    FieldSpec('effort', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('tawasulScaleIDEffort', 'ref:/scales', required: false, options: [], maxLength: 0),
    FieldSpec('comment', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('uploadedResponse', 'yn', required: false, options: ['N', 'Y'], maxLength: 0),
    FieldSpec('complete', 'yn', required: true, options: ['N', 'Y'], maxLength: 0),
    FieldSpec('completeDate', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('viewableStudents', 'yn', required: true, options: ['N', 'Y'], maxLength: 0),
    FieldSpec('viewableParents', 'yn', required: true, options: ['N', 'Y'], maxLength: 0),
    FieldSpec('tawasulPersonIDCreator', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDLastEdit', 'ref:/users', required: true, options: [], maxLength: 0),
  ],
  '/internal-assessment-entries': [
    FieldSpec('tawasulInternalAssessmentColumnID', 'ref:/internal-assessment-columns', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDStudent', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('attainmentValue', 'text', required: false, options: [], maxLength: 10),
    FieldSpec('attainmentDescriptor', 'text', required: false, options: [], maxLength: 100),
    FieldSpec('effortValue', 'text', required: false, options: [], maxLength: 10),
    FieldSpec('effortDescriptor', 'text', required: false, options: [], maxLength: 100),
    FieldSpec('comment', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('response', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDLastEdit', 'ref:/users', required: true, options: [], maxLength: 0),
  ],
  '/invoice-fees': [
  ],
  '/invoices': [
  ],
  '/lessons': [
    FieldSpec('tawasulCourseClassID', 'ref:/classes', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulUnitID', 'ref:/units', required: false, options: [], maxLength: 0),
    FieldSpec('date', 'date', required: true, options: [], maxLength: 0),
    FieldSpec('timeStart', 'time', required: true, options: [], maxLength: 0),
    FieldSpec('timeEnd', 'time', required: true, options: [], maxLength: 0),
    FieldSpec('name', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('summary', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('description', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('teachersNotes', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('homework', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('homeworkDueDateTime', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('homeworkDetails', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('viewableStudents', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('viewableParents', 'text', required: false, options: [], maxLength: 0),
  ],
  '/markbook-entries': [
    FieldSpec('tawasulMarkbookColumnID', 'ref:/markbook-columns', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDStudent', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('attainmentValue', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('attainmentValueRaw', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('attainmentDescriptor', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('attainmentConcern', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('effortValue', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('effortDescriptor', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('effortConcern', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('comment', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('modifiedAssessment', 'text', required: false, options: [], maxLength: 0),
  ],
  '/messages': [
    FieldSpec('tawasulSchoolYearID', 'ref:/school-years', required: false, options: [], maxLength: 0),
    FieldSpec('status', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('email', 'email', required: false, options: [], maxLength: 0),
    FieldSpec('messageWall', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('messageWall_dateStart', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('messageWall_dateEnd', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('sms', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('subject', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('body', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonID', 'ref:/users', required: false, options: [], maxLength: 0),
    FieldSpec('confidential', 'text', required: false, options: [], maxLength: 0),
  ],
  '/person-resets': [
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('key', 'text', required: true, options: [], maxLength: 40),
    FieldSpec('timestamp', 'datetime', required: false, options: [], maxLength: 0),
  ],
  '/person-status-logs': [
    FieldSpec('tawasulPersonID', 'ref:/users', required: true, options: [], maxLength: 0),
    FieldSpec('statusOld', 'choice', required: false, options: ['Full', 'Expected', 'Left', 'Pending Approval'], maxLength: 0),
    FieldSpec('statusNew', 'choice', required: false, options: ['Full', 'Expected', 'Left', 'Pending Approval'], maxLength: 0),
    FieldSpec('reason', 'long', required: true, options: [], maxLength: 0),
    FieldSpec('timestamp', 'datetime', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulPersonIDModified', 'ref:/users', required: false, options: [], maxLength: 0),
  ],
  '/personal-document-types': [
    FieldSpec('name', 'text', required: true, options: [], maxLength: 60),
    FieldSpec('description', 'long', required: true, options: [], maxLength: 255),
    FieldSpec('active', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('type', 'choice', required: false, options: ['Core', 'Additional'], maxLength: 0),
    FieldSpec('document', 'choice', required: false, options: ['Passport', 'ID Card', 'Visa', 'Document'], maxLength: 0),
    FieldSpec('fields', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('required', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('sequenceNumber', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('activePersonStudent', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('activePersonStaff', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('activePersonParent', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('activePersonOther', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('activeApplicationForm', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('activeDataUpdater', 'number', required: false, options: [], maxLength: 0),
  ],
  '/personal-documents': [
  ],
  '/roles': [
  ],
  '/username-formats': [
    FieldSpec('tawasulRoleIDList', 'text', required: false, options: [], maxLength: 255),
    FieldSpec('format', 'text', required: false, options: [], maxLength: 255),
    FieldSpec('isDefault', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('isNumeric', 'yn', required: false, options: ['Y', 'N'], maxLength: 0),
    FieldSpec('numericValue', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('numericIncrement', 'number', required: false, options: [], maxLength: 0),
    FieldSpec('numericSize', 'number', required: false, options: [], maxLength: 0),
  ],
  '/users': [
    FieldSpec('title', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('surname', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('firstName', 'text', required: true, options: [], maxLength: 0),
    FieldSpec('preferredName', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('officialName', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('gender', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('username', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('status', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('canLogin', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('email', 'email', required: false, options: [], maxLength: 0),
    FieldSpec('emailAlternate', 'email', required: false, options: [], maxLength: 0),
    FieldSpec('dob', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('studentID', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('dateStart', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('dateEnd', 'date', required: false, options: [], maxLength: 0),
    FieldSpec('phone1', 'phone', required: false, options: [], maxLength: 0),
    FieldSpec('phone1Type', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('phone2', 'phone', required: false, options: [], maxLength: 0),
    FieldSpec('address1', 'long', required: false, options: [], maxLength: 0),
    FieldSpec('address1District', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('address1Country', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('languageFirst', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('countryOfBirth', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulHouseID', 'ref:/houses', required: false, options: [], maxLength: 0),
    FieldSpec('tawasulRoleIDPrimary', 'ref:/roles', required: true, options: [], maxLength: 0),
    FieldSpec('tawasulRoleIDAll', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('lockerNumber', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('transport', 'text', required: false, options: [], maxLength: 0),
    FieldSpec('transportNotes', 'long', required: false, options: [], maxLength: 0),
  ],
};
